### ISSUE TITLE
Error while downloading 1000 images - "httplib.BadStatusLine"

### ISSUE THREAD

**Issue by dilipajm** [hardikvasa/google-images-download#107]
Here is my code:

```
keywords = "Lion,Dog,Cat"

response = google_images_download.googleimagesdownload()

arguments = {"keywords":keywords, "limit":limit, "chromedriver" :"/google_images_download/chromedriver"}  

paths = response.download(arguments)
```

**Error: after downloading 300~400 files, I get this error**

Traceback (most recent call last):
  File "google_images_download/google_images.py", line 82, in <module>
    download_images(keywords, 1000)
  File "google_images_download/google_images.py", line 12, in download_images
    paths = response.download(arguments)   #passing the arguments to the function
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 709, in _get_all_items
    download_status,download_message,return_image_name,absolute_path = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'],arguments['no_numbering'])
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 566, in download_image
    response = urlopen(req, None, timeout)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by KeyKy** [comment]
do it solved?

**Comment by dilipajm** [comment]
Yes, the issue got resolved when i placed a full path of chrome driver

**Comment by jillelajitta** [comment]
I gave the full path of chrome driver but still it is giving me that error.
