### ISSUE TITLE
Visually similar images flag gives error code 400

### ISSUE THREAD

**Issue by patrick-plutoflume** [hardikvasa/google-images-download#126]
Installed via `pip3 install google-images-download`, when running the command:

`googleimagesdownload -si "https://upload.wikimedia.org/wikipedia/commons/5/53/Wikipedia-logo-en-big.png" -l 20`

I get the error:

```
Item no.: 1 --> Item name = 2018-07-03 15_47_35
Evaluating...
https://upload.wikimedia.org/wikipedia/commons/5/53/Wikipedia-logo-en-big.png
HTTP Error 400: Bad Request
Starting Download...
Traceback (most recent call last):
  File "/Users/username/Library/Python/3.6/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/Users/username/Library/Python/3.6/lib/python/site-packages/google_images_download/google_images_download.py", line 888, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/Users/username/Library/Python/3.6/lib/python/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/Users/username/Library/Python/3.6/lib/python/site-packages/google_images_download/google_images_download.py", line 695, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/Users/username/Library/Python/3.6/lib/python/site-packages/google_images_download/google_images_download.py", line 660, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'
```

Running on Python 3.6, macOS 10.13.4 on a 2017 MBP

**Comment by patrick-plutoflume** [comment]
#59 seems to be having a similar error - I reused their url for demo purposes, but I get the same error against any url I try.

**Comment by hardikvasa** [comment]
@patrick-plutoflume i think this was an edge case scenario which would have caused this error. The fix was sent many commits away. Can you confirm if this is still an issue?

**Comment by hardikvasa** [comment]
Feel free to re-open the issue or comment on this thread if the issue still persist.
