### ISSUE TITLE
download fialed

### ISSUE THREAD

**Issue by marcelyz** [hardikvasa/google-images-download#131]
what's the problem?
`Marcel:Downloads$ googleimagesdownload -k "谭卓" -l 5

Item no.: 1 --> Item name = 谭卓
Evaluating...
<urlopen error [Errno 60] Operation timed out>
Starting Download...
Traceback (most recent call last):
  File "/Users/Marcel/anaconda/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/Users/Marcel/anaconda/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 888, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/Users/Marcel/anaconda/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/Users/Marcel/anaconda/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 695, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/Users/Marcel/anaconda/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 660, in _get_next_item
    start_line = s.find('rg_meta notranslate')`

**Comment by steve21124** [comment]
related to above topic, if it failed, probably will need a feature to continue from previous failed downlod

**Comment by hardikvasa** [comment]
The original issue reported should be fixed many commits back. The feature request to continue for where the download failed is being tracked in #128 . Thanks for reporting this!
