### ISSUE TITLE
httplib.BadStatusLine: '' SOLVED!

### ISSUE THREAD

**Issue by gabesantos** [hardikvasa/google-images-download#145]
Hi! I've been trying to use the following script to download some images but it gets stuck on the 31st image of the first search (Accordion). Any ideas on how to fix this?

SCRIPT:
`{
    "Records": [
        {
            "keywords": "Accordion",
            "limit": 50
        },
        {
            "keywords": "guitar",
            "limit": 50
        }
    ]
}`

ERROR:

`Traceback (most recent call last):
  File "/usr/local/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 888, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 709, in _get_all_items
    download_status,download_message,return_image_name,absolute_path = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'],arguments['no_numbering'])
  File "/usr/local/lib/python2.7/site-packages/google_images_download/google_images_download.py", line 566, in download_image
    response = urlopen(req, None, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''`

**Comment by gabesantos** [comment]
ok, it was just my firewall settings LOL now it's working

**Comment by hardikvasa** [comment]
Thanks. This should still give out a decent message instead of failing with this nasty. I will update the source accordingly. Closing this for now.

**Comment by peterliu1212** [comment]
I am facing the same problem. Is the problem really solved?
Error: httplib.BadStatusLine: ''
