### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by jubyshu** [hardikvasa/google-images-download#155]
Several weeks ago I can download images by it on my Mac, but now it suddenly don't work any more.
```
<urlopen error EOF occurred in violation of protocol (_ssl.c:833)>
Starting Download...
Traceback (most recent call last):
  File "/usr/local/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 893, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/usr/local/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 848, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/usr/local/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 697, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/usr/local/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 662, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by hardikvasa** [comment]
@jubyshu can you quickly forward me the complete query you are using? also are you behind a proxy?

**Comment by hardikvasa** [comment]
closing due to inactivity.
