### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by buaatian** [hardikvasa/google-images-download#158]
Traceback (most recent call last):
  File "/usr/python3/bin/googleimagesdownload", line 11, in <module>
    load_entry_point('google-images-download==2.4.2', 'console_scripts', 'googleimagesdownload')()
  File "/usr/python3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 893, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/usr/python3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 848, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/usr/python3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 697, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/usr/python3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 662, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'

Environment：Python 3.7 on CentOS 6

**Comment by hellogan** [comment]
For me this issue was because of the way python3 ssl. Following [this solution](https://stackoverflow.com/a/43855394) worked for me.

**Comment by hardikvasa** [comment]
#140 command will resolve the issue with python 3.7. Feel free to re-open the thread if the issue still persist.
