### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by dreamPoet** [hardikvasa/google-images-download#198]
Evaluating...
Could not open URL. Please check your internet connection and/or ssl settings
Starting Download...
Traceback (most recent call last):
  File "/home/shimeng/anaconda3/envs/pytorchEnv/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/home/shimeng/anaconda3/envs/pytorchEnv/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 904, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/home/shimeng/anaconda3/envs/pytorchEnv/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 859, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/home/shimeng/anaconda3/envs/pytorchEnv/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 705, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/home/shimeng/anaconda3/envs/pytorchEnv/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 670, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by dreamPoet** [comment]
I am using a proxy...

**Comment by februarysea** [comment]
I have the same problem. This issue may help you.
[https://github.com/hardikvasa/google-images-download/issues/95](url)

**Comment by rainyl** [comment]
I have the problem too....i am using a socks5 proxy, but it doesn't work, i also changed all 'google.com' to 'google.com.hk' as mentioned but no help...I am wondering whether it supports the socks5 proxy...

> I have the same problem. This[ issue](https://github.com/hardikvasa/google-images-download/issues/95) may help you.
