### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by alain2208** [hardikvasa/google-images-download#223]
Hi nice job ...but
when using chromedriver on windows 10 (the good version for the chrome installed) always got this error and download failed all

D:\driver>googleimagesdownload -k "dog" -l 101 -s medium -cd "d:/driver/chromedriver.exe"

Item no.: 1 --> Item name = dog
Evaluating...

DevTools listening on ws://127.0.0.1:59201/devtools/browser/4a97cbd2-429c-4ebb-979e-e9d61a225bb0
[0410/233117.134:WARNING:spdy_session.cc(3180)] Received HEADERS for invalid stream 25
Getting you a lot of images. This may take a few moments...
Reached end of Page.
Starting Download...
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\googleimagesdownload.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\google_images_download\google_images_download.py", line 904, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "d:\anaconda3\lib\site-packages\google_images_download\google_images_download.py", line 859, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "d:\anaconda3\lib\site-packages\google_images_download\google_images_download.py", line 720, in _get_all_items
    download_status,download_message,return_image_name,absolute_path = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'],arguments['no_numbering'],arguments['no_download'])
  File "d:\anaconda3\lib\site-packages\google_images_download\google_images_download.py", line 568, in download_image
    "User-Agent": "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.27 Safari/537.17"})
  File "d:\anaconda3\lib\urllib\request.py", line 329, in __init__
    self.full_url = url
  File "d:\anaconda3\lib\urllib\request.py", line 355, in full_url
    self._parse()
  File "d:\anaconda3\lib\urllib\request.py", line 382, in _parse
    self.type, rest = splittype(self._full_url)
  File "d:\anaconda3\lib\urllib\parse.py", line 936, in splittype
    _typeprog = re.compile('([^/:]+):(.*)', re.DOTALL)
  File "d:\anaconda3\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "d:\anaconda3\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "d:\anaconda3\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "d:\anaconda3\lib\sre_parse.py", line 865, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "d:\anaconda3\lib\sre_parse.py", line 834, in fix_flags
    flags |= SRE_FLAG_UNICODE
  File "d:\anaconda3\lib\enum.py", line 800, in __or__
    result = self.__class__(self._value_ | self.__class__(other)._value_)
  File "d:\anaconda3\lib\enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "d:\anaconda3\lib\enum.py", line 535, in __new__
    return cls._missing_(value)
  File "d:\anaconda3\lib\enum.py", line 764, in _missing_
    new_member = cls._create_pseudo_member_(value)
  File "d:\anaconda3\lib\enum.py", line 773, in _create_pseudo_member_
    _, extra_flags = _decompose(cls, value)
  File "d:\anaconda3\lib\enum.py", line 858, in _decompose
    for v, m in list(flag._value2member_map_.items())
RuntimeError: dictionary changed size during iteration

**Comment by hardikvasa** [comment]
@alain2208 do you get the same error when downloading <= 100 images? or is the error only seen when going beyond 100?

**Comment by hardikvasa** [comment]
Closing this thread due to inactivity. Follow the troubleshooting guide if you have issues with chromedriver on windows machine.

https://google-images-download.readthedocs.io/en/latest/troubleshooting.html#installing-the-chromedriver-with-selenium

Add more info here if you are still seeing this issue.
