### ISSUE TITLE
Automaticly Interrupted after open the browser

### ISSUE THREAD

**Issue by stoneeve415** [hardikvasa/google-images-download#226]
when I run "googleimagesdownload -cd "/usr/bin/chromedriver" -k "head" -l 101"
the chrome automaticlly open, but several minutes late,  it Interrupted. someone warm-hearted help me?

Item no.: 1 --> Item name = head
Evaluating...
Getting you a lot of images. This may take a few moments...
Traceback (most recent call last):
  File "/home/evestone/anaconda3/envs/py36/bin/googleimagesdownload", line 10, in <module>
    sys.exit(main())
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 910, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 859, in download
    raw_html = self.download_extended_page(url,arguments['chromedriver'])
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 183, in download_extended_page
    element = browser.find_element_by_tag_name("body")
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 530, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/evestone/anaconda3/envs/py36/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.86,platform=Linux 4.15.0-45-generic x86_64)

**Comment by stoneeve415** [comment]
I just find the proxy cause the problem(I am in China).
But i failed to use -px parameter, so i turn to browser, But chrome cannot install extension, so i use firefox.
1.change the file google_images_download line169
browser = webdriver.Chrome(chromedriver, chrome_options=options) to browser = webdriver.Firefox()
2.and then Configure vpn in firefox(use Proxy SwitchyOmega)
Finally i can download more than 100 images
