### ISSUE TITLE
Error: KeyError: 'ity'

### ISSUE THREAD

**Issue by zyoohv** [hardikvasa/google-images-download#232]
## setting 

python==3.6  

## command

```
googleimagesdownload --keywords "traffic accident" --limit 500 --size ">400*300" --output_directory google/ --chromedriver ./chromedriver --related_images
```

## error

```
Now Downloading - traffic accident -  0px; background-color: white;
Getting you a lot of images. This may take a few moments...
Reached end of Page.
Traceback (most recent call last):
  File "/Users/yonghui.zhang/anaconda3/bin/googleimagesdownload", line 10, in <module>
    sys.exit(main())
  File "/Users/yonghui.zhang/anaconda3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 909, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/Users/yonghui.zhang/anaconda3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 890, in download
    self._get_all_items(new_raw_html, main_directory, search_term + " - " + key, limit,arguments)
  File "/Users/yonghui.zhang/anaconda3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 720, in _get_all_items
    object = self.format_object(object)
  File "/Users/yonghui.zhang/anaconda3/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 257, in format_object
    formatted_object['image_format'] = object['ity']
KeyError: 'ity'
```

**Comment by hardikvasa** [comment]
@zyoohv this seems related to #234 although I am not very sure. I have made some changes to the `related_images` argument. Can you confirm if you are seeing the same issue after upgrading the lib to `2.7.0` version?

**Comment by hardikvasa** [comment]
closing the issue due to inactivity. Feel free to open this thread or comment here if the issue still persist.
