### ISSUE TITLE
DOWNLOAD ERROR FIXED

### ISSUE THREAD

**Issue by Nestak2** [hardikvasa/google-images-download#312]
See this quick and dirty [fix](https://github.com/hardikvasa/google-images-download/pull/298#issuecomment-603722006), it solved the download problem for me! I just erased the pre-existing code in the file `google_images_download.py` and substituted it with the provided code by the user

**Comment by hermannsblum** [comment]
Nope, just tested, that fix does not work: 

```
python3.6/site-packages/google_images_download/google_images_download.py in _get_image_objects(self, s)
    756         object_raw = str(s[start_object:end_object])
    757         object_decode = bytes(object_raw, "utf-8").decode("unicode_escape")
--> 758         image_objects = json.loads(object_decode)[31][0][12][2]
    759         image_objects = [x for x in image_objects if x[0]==1]
    760         return image_objects

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by nuertey2020** [comment]
Likewise still observing the same error that @hermannsblum is seeing even after the fix @Nestak2. My observed error is:

```
Item no.: 1 --> Item name = Still Life with a Skull and a Writing Quill
Evaluating...
Starting Download...
Traceback (most recent call last):
  File "/home/rena/MyEnv37/bin/googleimagesdownload", line 8, in <module>
    sys.exit(main())
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 1011, in main
    paths,errors = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 838, in download
    paths, errors = self.download_executor(arguments)
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 965, in download_executor
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 768, in _get_all_items
    image_objects = self._get_image_objects(page)
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 758, in _get_image_objects
    image_objects = json.loads(object_decode)[31][0][12][2]
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by nuertey** [comment]
Likewise still observing the same error that @hermannsblum is seeing even after the fix @Nestak2. My observed error is:
```
Item no.: 1 --> Item name = Still Life with a Skull and a Writing Quill
Evaluating...
Starting Download...
Traceback (most recent call last):
  File "/home/rena/MyEnv37/bin/googleimagesdownload", line 8, in <module>
    sys.exit(main())
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 1011, in main
    paths,errors = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 838, in download
    paths, errors = self.download_executor(arguments)
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 965, in download_executor
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 768, in _get_all_items
    image_objects = self._get_image_objects(page)
  File "/home/rena/MyEnv37/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 758, in _get_image_objects
    image_objects = json.loads(object_decode)[31][0][12][2]
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by cooperdk** [comment]
I get an identical error.

`  File "c:\python\lib\site-packages\google_images_download\google_images_download.py", line 832, in download
    paths, errors = self.download_executor(arguments)
  File "c:\python\lib\site-packages\google_images_download\google_images_download.py", line 959, in download_executor
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "c:\python\lib\site-packages\google_images_download\google_images_download.py", line 762, in _get_all_items
    image_objects = self._get_image_objects(page)
  File "c:\python\lib\site-packages\google_images_download\google_images_download.py", line 753, in _get_image_objects
    image_objects = json.loads(object_decode)[31][0][12][2]
  File "c:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by AmitSharma1127** [comment]
Same error

`Traceback (most recent call last):
  File "C:\Users\Amit\Anaconda3\Scripts\googleimagesdownload-script.py", line 11, in <module>
    load_entry_point('google-images-download==2.8.0', 'console_scripts', 'googleimagesdownload')()
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 1006, in main      
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 833, in download   
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 960, in download_executor
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 763, in _get_all_items
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 753, in _get_image_objects
  File "C:\Users\Amit\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Amit\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Amit\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by AmitSharma1127** [comment]
Same error:

```
Traceback (most recent call last):
  File "C:\Users\Amit\Anaconda3\Scripts\googleimagesdownload-script.py", line 11, in <module>
    load_entry_point('google-images-download==2.8.0', 'console_scripts', 'googleimagesdownload')()
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 1006, in main      
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 833, in download   
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 960, in download_executor
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 763, in _get_all_items
  File "C:\Users\Amit\Anaconda3\lib\site-packages\google_images_download-2.8.0-py3.7.egg\google_images_download\google_images_download.py", line 753, in _get_image_objects
  File "C:\Users\Amit\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Amit\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Amit\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Geremia** [comment]
This seems to be a duplicate of #315.

**Comment by hardikvasa** [comment]
Thanks for reporting\! This is now fixed. The parsing code was completely rewritten in May 2026 to work with modern Google Images. The tool now properly downloads images and handles Google's current HTML structure.
