### ISSUE TITLE
Never getting any images

### ISSUE THREAD

**Issue by mp3cko** [hardikvasa/google-images-download#325]
I just cannot get this module to work, it always returns 0 results. Here is a screenshot from the CLI

![image](https://user-images.githubusercontent.com/56165587/91612715-47ebac80-e97e-11ea-9c9c-8da3248c204b.png)

And here is an example where it is used inside a function:

```py
def changewallpaper(keyword):
    resp = google_images_download.googleimagesdownload() # init class
    args = {
            "keywords": f"{keyword} wallpaper",
            "limit": 1,
            "size": "large",
            "print_urls": True
        } #pass args
    download_folder = fr"{os.getcwd()}\downloads\{keyword} wallpaper"
    paths = resp.download(args) #save downloaded image paths to paths var
    print(paths) # printing paths```

**Comment by willowec** [comment]
Having the same problem. Has some change in Google's api broken it?

**Comment by mp3cko** [comment]
There is no API here, its web scraping. But yeah it got broken.

**Comment by protrolium** [comment]
Also broken for me:

Item no.: 1 --> Item name = Trump Face
Evaluating...
Getting you a lot of images. This may take a few moments...
Reached end of Page.
Traceback (most recent call last):
  <br>File "/Users/[username]/.pyenv/versions/3.8.2/bin/googleimagesdownload", line 11, in <module>
    load_entry_point('google-images-download==2.8.0', 'console_scripts', 'googleimagesdownload')()

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google_images_download/google_images_download.py", line 1072, in main
    paths,errors = response.download(arguments)  #wrapping response in a variable just for consistency

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google_images_download/google_images_download.py", line 900, in download
    paths, errors = self.download_executor(arguments)

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google_images_download/google_images_download.py", line 1020, in download_executor
    images, tabs = self.download_extended_page(url,arguments['chromedriver'])

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google_images_download/google_images_download.py", line 265, in download_extended_page
    images = self._image_objects_from_pack(self._extract_data_pack_extended(source))

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google_images_download/google_images_download.py", line 148, in _image_objects_from_pack
    image_objects = json.loads(data)[31][0][12][2]

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)

File "/Users/[username]/.pyenv/versions/3.8.2/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1897 column 1 (char 133213)

**Comment by qiyang77** [comment]
Same to me, not solved yet.

**Comment by nvnnghia** [comment]
+1

**Comment by yogesch** [comment]
+2

**Comment by eyjho** [comment]
Broken for me too

```
Could not open URL. Please check your internet connection and/or ssl settings 
If you are using proxy, make sure your proxy settings is configured correctly
```

**Comment by jap101** [comment]
https://github.com/hardikvasa/google-images-download/issues/316
looks similar to an issue i had a few weeks ago

**Comment by yogesch** [comment]
The patched version [here](https://github.com/Joeclinton1/google-images-download) doesn't work either

**Comment by pickdani** [comment]
\+

**Comment by mp3cko** [comment]
> Broken for me too
> 
> ```
> Could not open URL. Please check your internet connection and/or ssl settings 
> If you are using proxy, make sure your proxy settings is configured correctly
> ```

That error is what I am getting in [this ](https://github.com/Joeclinton1/google-images-download) fork as well

**Comment by Joeclinton1** [comment]
I have fixed this error in the latest commit of [patch-1](https://github.com/Joeclinton1/google-images-download)

To be more specific I have fixed the error below:
```
Could not open URL. Please check your internet connection and/or ssl settings 
If you are using proxy, make sure your proxy settings is configured correctly
```

The other error (the first one mentioned) is what my patch was created to solve, and it still does.

**Comment by yogesch** [comment]
I think there are two separate errors we're talking about here. 

The first is this:


```
#googleimagesdownload -k "apples" -l 20

Item no.: 1 --> Item name = apples
Evaluating...
Starting Download...


Unfortunately all 20 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0


Everything downloaded!
Total errors: 0
Total time taken: 1.8162510395050049 Seconds

```


The second is this:
```
Could not open URL. Please check your internet connection and/or ssl settings 
If you are using proxy, make sure your proxy settings is configured correctly
```

The current code, including the patched version currently still has the first error.

**Comment by dmitryponv** [comment]
Line 717 it searches for "rg_meta notranslate" in the returned page data which does not exist anymore

**Comment by 610yilingliu** [comment]
Same issue

**Comment by BigDanTheOne** [comment]
I faced the same problem but simply added sudo and this solved the problem for me (Colab)

**Comment by amrahsmaytas** [comment]
> I faced the same problem but simply added sudo and this solved the problem for me (Colab)

Can you please share the modified code  regarding the google colab?

**Comment by qiyang77** [comment]
I maybe find a better choice for normal user, a GUI version images download tool to pull images from Google, Bing and Baidu,[https://github.com/sczhengyabin/Image-Downloader](url), and this working well for me.

**Comment by yogesch** [comment]
That's not necessarily a better choice. It is very processor intensive. The
GUI is a nice touch. But I wasn't able to run it on a terminal-only
machine. Of course if this one doesn't work at all then maybe yes.

**Comment by yogesch** [comment]
He means to run the command with sudo.

**Comment by BigDanTheOne** [comment]
> > I faced the same problem but simply added sudo and this solved the problem for me (Colab)
> 
> Can you please share the modified code regarding the google colab?

https://colab.research.google.com/drive/1RlHZWi4M7jZIaGjsqxIQokqrIFCTy5Hi?usp=sharing

**Comment by hoangphuc1998** [comment]
I'm facing the same problem. Does anyone have solution for this?

**Comment by k0a8t1o6** [comment]
Same issue. Has the front end of Google Images changed?

**Comment by Joeclinton1** [comment]
@k0a8t1o6 @hoangphuc1998  My patch-1 still works and fixes this issue, install it by running the below code in the cmd

git clone https://github.com/Joeclinton1/google-images-download.git
cd google-images-download && python setup.py install

**Comment by umustbeloggedintododat** [comment]
I still have the original and when I run to get your patch it was a success but I still get the same error

**Comment by umustbeloggedintododat** [comment]
nvm I got it but where do the images download

**Comment by Joeclinton1** [comment]
@umustbeloggedintododat you need to specify a directory, with the argument output_directory, if not specified it will output to your downloads folder.

**Comment by cooperdk** [comment]
> I maybe find a better choice for normal user, a GUI version images download tool to pull images from Google, Bing and Baidu,[https://github.com/sczhengyabin/Image-Downloader](url), and this working well for me.

You may not.
This is command-line or run as a module (both actually), ... if we're looking for a Python module, then we need that, not a gui.

**Comment by vool** [comment]
uninstall the pip package first
 `pip uninstall google_images_download`

> I still have the original and when I run to get your patch it was a success but I still get the same error

**Comment by jamiemonksuk** [comment]
@Joeclinton1 I'm getting this error every time, even with basic arguments. Am I doing something fundamentally wrong? Cheers!

Evaluating...
str() takes at most 1 argument (2 given)
Image objects data unpacking failed. Please leave a comment with the above error at https://github.com/hardikvasa/google-images-download/pull/298

**Comment by Joeclinton1** [comment]
@jamiemonksuk That error probably arises from this line in the code:
`object_raw = str(page[start_object:end_object])`

I'm not getting any error, so maybe you don't have the current version. It's very unlikely to be due to any arguments you've given.

**Comment by kaloomte** [comment]
Hi everyone, while i try download similar images with related image URL i got this error.
![google-downloads-error1](https://user-images.githubusercontent.com/42833660/110987479-2d0fe100-8380-11eb-8b4d-bcd7d39825e1.png)

**Comment by kruemmelbande** [comment]
Same issue...
