### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nonauthor** [hardikvasa/google-images-download#374]
I tried use the method that 
git clone https://github.com/Joeclinton1/google-images-download.git
cd google-images-download && python setup.py install
But it still can not work.

**Comment by nonauthor** [comment]
Item no.: 1 --> Item name = Soraya Mendivil olympic champion
Evaluating...
Traceback (most recent call last):
  File "D:\ZMJ\pythonProject\SEV_data\download_image.py", line 11, in <module>
    paths = response.download(arguments)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\google_images_download-2.8.0-py3.9.egg\google_images_download\google_images_download.py", line 970, in download
  File "C:\Users\Administrator\anaconda3\lib\site-packages\google_images_download-2.8.0-py3.9.egg\google_images_download\google_images_download.py", line 1118, in download_executor
  File "C:\Users\Administrator\anaconda3\lib\site-packages\google_images_download-2.8.0-py3.9.egg\google_images_download\google_images_download.py", line 906, in _get_all_items
TypeError: 'NoneType' object is not subscriptable
Getting URLs without downloading images...
'NoneType' object is not subscriptable

**Comment by srkmish** [comment]
Same issue. Is there a fix for this?

**Comment by moisty70** [comment]
No fix

**Comment by fzhxk** [comment]
chrome 120.0.6099.71  2023/12/11
They moved the “info” parameter to data [25], where `google_images_download.py`
411        if info is None:
412            info = data[11]
>>>>>>>
413        if info is None:
414            info = data[25]
>>>>>>>    
Hope to help you!

**Comment by JYJ9701** [comment]
> chrome 120.0.6099.71 2023/12/11 They moved the “info” parameter to data [25], where `google_images_download.py` 411 if info is None: 412 info = data[11]
> 
> > > > > > > >
> 
> 413 if info is None: 414 info = data[25]
> 
> > > > > > > >
> 
> Hope to help you!

it works！thX!
