### ISSUE TITLE
search by url

### ISSUE THREAD

**Issue by marcelloexp386** [hardikvasa/google-images-download#59]
Dear all, I would like to search for images using the search  by image. I think that this accomplished by providing the (-u + url ) in the CLI but I have problems . 

Originallly, the problem was with the name of the file and of the directory where the download has to occur. Specifically, Windows do not accept name of directories and file with the ":" character, so I changed both image_name with image_name.replace(':',"x") and dir_name with the same .replace function in the google_images_download.py file.
 
Unfortunately, the correction was not sufficient because if I run the following CLI :

> py google_images_download.py -k "adidas" -u "https://www.adidas.it/dis/dw/image/v2/aagl_prd/on/demandware.static/-/Sites-adidas-products/default/dwc78be248/zoom/C77124_01_standard.jpg?sh=600&strip=false&sw=600" -l 20

I receive the following error msg: "***** This search result did not return any results...please try a different search filter *****"

Which is quite strange because the search works correctly if I simply eliminate the "- u image_url" and I simply run from the CLI:

 > py google_images_download.py -k "adidas"  -l 20

Did someone encounter this problem before and solved it? Is there a way to upload the image from a jpg or png file on your local directory instead of providing the web address of the same image?

Thanks

PS I run Python 3.6 and Windows 10

**Comment by hardikvasa** [comment]
@marcelloexp386 

For the first issue with `:` i think you are using the older version of this script. A few commits back, this was changed to use `_` instead of `:` because of compatibility issues in windows. Please update your script to the latest version of this repo.

Regarding the second issue, the correct command to search by image is `si` or `similar_images`. You can use your command...just replace -u with -si. The '-u' is used where you can copy google images link from your browser and just paste it here and it will download all the images from that page.

The description of -u might be little confusion. I will have it edited. Do let me know if that works for you.

**Comment by marcelloexp386** [comment]
Thanks @hardikvasa for your kind answer.
1) solved
2) tried your suggestion but still doesn't work. I was looking for example for images similar to wikipedia one:

> py google_images_download.py -si "https://upload.wikimedia.org/wikipedia/commons/5/53/Wikipedia-logo-en-big.png" -l 20

but it gives me the following errors:

Item no.: 1 --> Item name = 2018-04-03 13_13_29
Evaluating...
HTTP Error 400: Bad Request
Starting Download...
Traceback (most recent call last):
  File "google_images_download.py", line 775, in <module>
    errorCount = bulk_download(search_keyword,suffix_keywords,prefix_keywords,limit,main_directory)
  File "google_images_download.py", line 645, in bulk_download
    items,errorCount = _get_all_items(raw_html,main_directory,dir_name,limit)    #get all image items and download images
  File "google_images_download.py", line 574, in _get_all_items
    object, end_content = _get_next_item(page)
  File "google_images_download.py", line 540, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by hardikvasa** [comment]
@marcelloexp386 Unfortunately I could not reproduce this error.

When I tried using your query from a windows 10, python 3 environment, I could successfully download  all 20 images similar to the one you provided in the link.

Do you see this error for different image links or only this one image?
