### ISSUE TITLE
Error message when no arguments provided

### ISSUE THREAD

**Issue by knrdl** [hardikvasa/google-images-download#75]
Error message is shown instead of the help text when no arguments are provided

```
Traceback (most recent call last):
  File "/usr/local/bin/google_images_download.py", line 793, in <module>
    main()
  File "/usr/local/bin/google_images_download.py", line 785, in main
    response.download(arguments)
  File "/usr/local/bin/google_images_download.py", line 707, in download
    raise ValueError('Keywords is a required argument!')
ValueError: Keywords is a required argument!
```

**Comment by hardikvasa** [comment]
@knrdl Thanks for opening this issue. I will add a small logic where it would ask user to enter the keyword and not throw an error. Or at the very least print out a help message and exit.

**Comment by hardikvasa** [comment]
The script now throws a helpful message when the keyword argument is not provided.

Thanks.
