### ISSUE TITLE
better error handling in download_file

### ISSUE THREAD

**Issue by hegman12** [hardikvasa/google-images-download#87]
I was trying out the tool and its really cool! But i noticed the error handling in download_file is not up to the mark. I was behind proxy and my internet was particularly slow. When i tried, i kept getting below error -

`Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\googleimagesdownload-script.py", line 11, in <module>
    load_entry_point('google-images-download==2.0.4', 'console_scripts', 'googleimagesdownload')()
  File "C:\Anaconda3\lib\site-packages\google_images_download-2.0.4-py3.6.egg\google_images_download\google_images_download.py", line 819, in main
  File "C:\Anaconda3\lib\site-packages\google_images_download-2.0.4-py3.6.egg\google_images_download\google_images_download.py", line 777, in download
  File "C:\Anaconda3\lib\site-packages\google_images_download-2.0.4-py3.6.egg\google_images_download\google_images_download.py", line 666, in _get_all_items
  File "C:\Anaconda3\lib\site-packages\google_images_download-2.0.4-py3.6.egg\google_images_download\google_images_download.py", line 577, in download_image
UnboundLocalError: local variable 'output_file' referenced before assignment`

It looks like below finally block gets executed for whatever reason, there will not be any meaningful error thrown to user. It will be good if you add this message.

`finally:
output_file.close()`

**Comment by HappyAdjustableSpanners** [comment]
I am also having this problem

**Comment by hardikvasa** [comment]
Thanks!
UnboundLocalError bug should now be resolved. @hegman12 , @HappyAdjustableSpanners could you download the latest version of this repo and try again?

**Comment by hardikvasa** [comment]
The latest version of this script should resolve this issue. Closing this issue.
If you guys do still see this issue, do let me know.

**Comment by hegman12** [comment]
Hey, Thanks for quick response!
