### ISSUE TITLE
Is this error related to proxy settings?

### ISSUE THREAD

**Issue by gitfourteen** [hardikvasa/google-images-download#95]
copied error info as follows. What is the argument settings if linking google by VPS/SS? Thanks.

(py3) MAC:~ user$ googleimagesdownload -k "Ivanka Trump" -f png -t face **-px 13.231.---.---:----**

Item no.: 1 --> Item name = Ivanka Trump
Evaluating...
<urlopen error [Errno 54] Connection reset by peer>
Starting Download...
Traceback (most recent call last):
  File "/Users/anaconda2/envs/py3/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/Users/anaconda2/envs/py3/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 835, in main
    response.download(arguments)
  File "/Users/anaconda2/envs/py3/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 793, in download
    items,errorCount = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/Users/anaconda2/envs/py3/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 657, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/Users/anaconda2/envs/py3/lib/python3.6/site-packages/google_images_download/google_images_download.py", line 623, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by hardikvasa** [comment]
Hi @gitfourteen 

`<urlopen error [Errno 54] Connection reset by peer>` this seems to me like the query could not even download the raw HTML page. It is mostly because the page could not be retrieved over the network and could most likely be proxy related.

Can you try a different IP address to see if that works? I used the query you mentioned and it works fine for me though.

Closing this issue for now. Do let me know if this works out for you.
